PREFIX lack:        <https://purl.net/climatesense/lack/ns#>
PREFIX lack-entity: <https://purl.net/climatesense/lack/entity/>
PREFIX lack-type:   <https://purl.net/climatesense/lack/type/>
PREFIX owl:         <http://www.w3.org/2002/07/owl#>
PREFIX rdf:         <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#>

SELECT
    ?type
   (COUNT(DISTINCT ?entity) AS ?count)
   (COUNT(DISTINCT ?isWikidata) AS ?wikidata)
   (COUNT(DISTINCT ?isDBpedia) AS ?dbpedia)
WHERE {
    {?entity rdf:type ?type . FILTER(?type = lack:Person) }
    UNION
    {?entity rdf:type ?type . FILTER(?type = lack:Collective ) }

    OPTIONAL {
        ?entity owl:sameAs ?isWikidata
        FILTER(STRSTARTS(STR(?isWikidata), "https://www.wikidata.org/"))
    }.
    OPTIONAL {
            ?entity owl:sameAs ?isDBpedia
            FILTER(STRSTARTS(STR(?isDBpedia), "http://dbpedia.org/"))
        }.

} group by ?type
