PREFIX lack:        <https://purl.net/climatesense/lack/ns#>
PREFIX lack-entity: <https://purl.net/climatesense/lack/entity/>
PREFIX lack-type:   <https://purl.net/climatesense/lack/type/>
PREFIX owl:         <http://www.w3.org/2002/07/owl#>
PREFIX rdf:         <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#>

SELECT
   (COUNT(?entity) AS ?count)
   ?source
WHERE {
{{
SELECT ?entity ?source
where    { 
        ?entity rdf:type rdf:Statement .
            ?entity rdfs:seeAlso ?evidenceLink .
            
         BIND(
             IF(STRSTARTS(?evidenceLink,"https://"),
             REPLACE(?evidenceLink, "^https://([^/]+).*$","https://$1"),
             REPLACE(?evidenceLink, "^http://([^/]+).*$","https://$1") )
             AS ?source)
    }
}}
}
group by ?source
