PREFIX lack: <https://purl.net/climatesense/lack/ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

SELECT ?relation (COUNT(*) AS ?count)
WHERE {
  ?s a rdf:Statement ; rdf:predicate ?relation .
}
GROUP BY ?relation
ORDER BY DESC(?count)
